netbox_transceiver/urls.py
from django.urls import  path

from . import models, views
from netbox.views.generic import ObjectChangeLogView

app_name = "transceiver"

urlpatterns = (

    # TransceiverTypes
    path('transceivertype/', views.TransceiverTypeListView.as_view(), name='transceivertype_list'),
    path('transceivertype/add/', views.TransceiverTypeEditView.as_view(), name='transceivertype_add'),
    path('transceivertype/delete/', views.TransceiverTypeBulkDeleteView.as_view(), name='transceivertype_bulk_delete'),
    path('transceivertype/edit/', views.TransceiverTypeBulkEditView.as_view(), name='transceivertype_bulk_edit'),
    path('transceivertype/<int:pk>/', views.TransceiverTypeView.as_view(), name='transceivertype'),
    path('transceivertype/<int:pk>/edit/', views.TransceiverTypeEditView.as_view(), name='transceivertype_edit'),
    path('transceivertype/<int:pk>/delete/', views.TransceiverTypeDeleteView.as_view(), name='transceivertype_delete'),
    path('transceivertype/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='transceivertype_changelog', kwargs={'model': models.TransceiverType}),

    # TransceiverTypesProfile
    path('transceivertypeprofile/', views.TransceiverTypeProfileListView.as_view(), name='transceivertypeprofile_list'),
    path('transceivertypeprofile/add/', views.TransceiverTypeProfileEditView.as_view(), name='transceivertypeprofile_add'),
    path('transceivertypeprofile/delete/', views.TransceiverTypeProfileBulkDeleteView.as_view(), name='transceivertypeprofile_bulk_delete'),
    path('transceivertypeprofile/edit/', views.TransceiverTypeProfileBulkEditView.as_view(), name='transceivertypeprofile_bulk_edit'),
    path('transceivertypeprofile/<int:pk>/', views.TransceiverTypeProfileView.as_view(), name='transceivertypeprofile'),
    path('transceivertypeprofile/<int:pk>/edit/', views.TransceiverTypeProfileEditView.as_view(), name='transceivertypeprofile_edit'),
    path('transceivertypeprofile/<int:pk>/delete/', views.TransceiverTypeProfileDeleteView.as_view(), name='transceivertypeprofile_delete'),
    path('transceivertypeprofile/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='transceivertypeprofile_changelog', kwargs={'model': models.TransceiverTypeProfile}),

    # Transceiver
    path('transceiver/', views.TransceiverListView.as_view(), name='transceiver_list'),
    path('transceiver/add/', views.TransceiverEditView.as_view(), name='transceiver_add'),
    path('transceiver/delete/', views.TransceiverBulkDeleteView.as_view(), name='transceiver_bulk_delete'),
    path('transceiver/edit/', views.TransceiverBulkEditView.as_view(), name='transceiver_bulk_edit'),
    path('transceiver/<int:pk>/', views.TransceiverView.as_view(), name='transceiver'),
    path('transceiver/<int:pk>/edit/', views.TransceiverEditView.as_view(), name='transceiver_edit'),
    path('transceiver/<int:pk>/delete/', views.TransceiverDeleteView.as_view(), name='transceiver_delete'),
    path('transceiver/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='transceiver_changelog', kwargs={'model': models.Transceiver}),

    )

netbox_transceiver/models.py
from django.urls import reverse

from django.db import models
from netbox.models import NetBoxModel

from .choices import *

class TransceiverTypeProfile(NetBoxModel):
    profile = models.CharField(
        max_length=50,
        unique=True,
    )
    group = models.CharField(
        max_length=50,
        choices=TransceiverTypeProfileGroupChoices)

    class Meta:
        ordering = ('group', 'profile')
        constraints = (
            models.UniqueConstraint(
                fields=('group', 'profile'),
                name='%(app_label)s_%(class)s_unique_group_profile'
            ),
        )

    def __str__(self):
        return self.profile

    def get_absolute_url(self):
        return reverse('plugins:netbox_transceiver:transceivertypeprofile', args=[self.pk])

class TransceiverType(NetBoxModel):
    """
    A TransceiverType represents a hardware element that can be installed on a interface.
    It do not change the behavior of that interface, it's simply there and is now tracked
    """

    manufacturer = models.ForeignKey(
        to='dcim.Manufacturer',
        on_delete=models.PROTECT,
        related_name='transceiver_types'
    )
    model = models.CharField(
        max_length=100
    )
    part_number = models.CharField(
        max_length=50,
        blank=True,
        help_text=('Discrete part number (optional)')
    )
    physic = models.CharField(
        max_length=50,
        choices=TransceiverTypePhysicChoices,
        blank=True,
        null=True,
        verbose_name='Physical connection',
        help_text=('The pyhsical connection of the transceiver (optional)')
    )
    form = models.CharField(
        max_length=50,
        choices=TransceiverTypeFormChoices,
        blank=True,
        null=True,
        verbose_name='Form factor',
        help_text=('The form factor of the transceiver (optional)')
    )
    tx_power_min = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        verbose_name='Min Tx Power (dBm)'
    )
    tx_power_max = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        verbose_name='Max Tx Power (dBm)'
    )
    rx_power_min = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        verbose_name='Min Rx Power (dBm)'
    )
    rx_power_max = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
        verbose_name='Max Rx Power (dBm)'
    )
    profiles = models.ManyToManyField(
        to=TransceiverTypeProfile,
        related_name='profiles',
        blank=True,
        verbose_name='Profiles',
        )
    comments = models.TextField(
        blank=True
        )

    #clone_fields = ('manufacturer')

    prerequisite_models = (
        'dcim.Manufacturer',
    )

    class Meta:
        ordering = ('manufacturer', 'model')
        constraints = (
            models.UniqueConstraint(
                fields=('manufacturer', 'model'),
                name='%(app_label)s_%(class)s_unique_manufacturer_model'
            ),
        )

    def __str__(self):
        return self.model

    def get_absolute_url(self):
        return reverse('plugins:netbox_transceiver:transceivertype', args=[self.pk])

    def power_budget_max(self):
        if self.rx_power_min and self.tx_power_min:
            budget = self.rx_power_min - self.tx_power_min
            if budget < 0:
                budget = budget * -1
            return budget

    def power_budget_min(self):
        if self.rx_power_max and self.tx_power_max:
            budget = self.rx_power_max - self.tx_power_max
            if budget < 0:
                budget = budget * -1
            return budget

class Transceiver(NetBoxModel):
    """
    The Transceiver represents the field-installable component within a interface. 
    One interface can house one transceiver
    """
    device = models.ForeignKey(
        to='dcim.Device',
        on_delete=models.CASCADE,
        related_name='transceivers'
    )
    interface = models.OneToOneField(
        to='dcim.Interface',
        on_delete=models.CASCADE,
        related_name='transceivers'
    )
    transceiver_type = models.ForeignKey(
        to=TransceiverType,
        on_delete=models.PROTECT,
        related_name='instances'
    )
    profile = models.ForeignKey(
            to=TransceiverTypeProfile,
            on_delete=models.PROTECT,
            related_name='transceiver_profile'
        )
    status = models.CharField(
        max_length=50,
        choices=TransceiverStatusChoices,
        default=TransceiverStatusChoices.STATUS_PLANNED
    )
    serial = models.CharField(
        max_length=50,
        blank=True,
        verbose_name='Serial number'
    )
    description = models.CharField(
        max_length=150,
        blank=True,
    )
    asset_tag = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        unique=True,
        verbose_name='Asset tag',
        help_text=('A unique tag used to identify this device')
    )

    class Meta:
        ordering = ('interface',)
        verbose_name = 'Transceiver'
        verbose_name_plural = 'Transceivers'

    def __str__(self):
        return f'{self.device.name}: {self.interface} ({self.pk})'

    #def save(self, *args, **kwargs):
    #    is_new = not bool(self.pk)

    def get_absolute_url(self):
        return reverse('plugins:netbox_transceiver:transceiver', args=[self.pk])

    def get_status_color(self):
        return TransceiverStatusChoices.colors.get(self.status)

    def name(self):
        return f'{self.device.name}: {self.interface}'

netbox_transceiver/templates/netbox_transceiver/device_include.html
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        Related Transceivers
    </h5>
    <div class="card-body">
        {% render_table related_transceiver_table 'inc/table.html' %}
    </div>
    <div class="card-footer text-end noprint">
        <a href="{% url 'plugins:netbox_transceiver:transceiver_add' %}?device={{ object.pk }}&return_url={% url 'dcim:device' pk=object.pk %}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i>
            Add Transceiver
        </a>
    </div>

</div>

netbox_transceiver/templates/netbox_transceiver/transceiver.html
{% extends 'generic/object.html' %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block title %}{{ object.device }} {{ object.interface }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Transceiver</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <td>Device</td>
                        <td>{{ object.device|linkify }}</td>
                    </tr>
                    <tr>
                        <td>Interface</td>
                        <td>{{ object.interface|linkify }}</td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td>{{ object.transceiver_type|linkify }}</td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td>{{ object.profile|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Status</th>
                        <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
                    </tr>
                </table>
            </div>
        </div>
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/related_objects.html' %}
    </div>
</div>
{% endblock content %}

netbox_transceiver/templates/netbox_transceiver/transceivertype.html
{% extends 'generic/object.html' %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'plugins:netbox_transceiver:transceivertype_list' %}?manufacturer_id={{ object.manufacturer.pk }}">{{ object.manufacturer }}</a></li>
{% endblock %}

{% block title %}{{ object.manufacturer }} {{ object.model }}{% endblock %}



{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Transceiver Type</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <td>Manufacturer</td>
                        <td>{{ object.manufacturer|linkify }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Model</th>
                        <td>{{ object.model }}</td>
                    </tr>
                    <tr>
                        <td>Part Number</td>
                        <td>{{ object.part_number|placeholder }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Description</th>
                        <td>{{ object.description|placeholder }}</td>
                    </tr>
                    <tr>
                        <td>Weight</td>
                        <td>
                            {% if object.weight %}
                            {{ object.weight|floatformat }} {{ object.get_weight_unit_display }}
                            {% else %}
                            {{ ''|placeholder }}
                            {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card">
            <h5 class="card-header">Specifications</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <td>Physical connection</td>
                        <td>{{ object.get_physic_display|placeholder}}</td>
                    </tr>
                    <tr>
                        <td>Form factor</td>
                        <td>{{ object.get_form_display|placeholder }}</td>
                    </tr>
                    <tr>
                        <td>Tx Power</td>
                        <td>min. {{ object.tx_power_min|placeholder }} dBm / max. {{ object.tx_power_max|placeholder }} dBm</td>
                    </tr>
                    <tr>
                        <td>Rx Power</td>
                        <td>min. {{ object.rx_power_min|placeholder }} dBm / max. {{ object.rx_power_max|placeholder }} dBm</td>
                    </tr>
                    <tr>
                        <td>Power budget</td>
                        <td>min. {{ object.power_budget_min|placeholder  }} dB / max. {{ object.power_budget_max|placeholder  }} dB</td>
                    </tr>
                </table>
            </div>
        </div>
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/related_objects.html' %}
    </div>
</div>
{% endblock content %}

netbox_transceiver/templates/netbox_transceiver/transceivertypeprofile.html
{% extends 'generic/object.html' %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block title %}{{ object.group }} {{ object.profile }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Transceiver Type</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <td>Profile</td>
                        <td>{{ object.profile }}</td>
                    </tr>
                    <tr>
                        <td>Group</td>
                        <td>{{ object.group }}</td>
                    </tr>
                </table>
            </div>
        </div>
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/related_objects.html' %}
    </div>
</div>
{% endblock content %}